

const dataarray = [{url: 'https://cdn.historycollection.com/wp-content/uploads/2025/06/article_image_685f49f0a5abf1751075312.jpg', title: 'Foot Binding', country: 'China', desc: 'For nearly a thousand years, foot binding was a symbol of beauty and status among Chinese women. Tiny, delicately shaped feet—known as “lotus feet”—were seen as the height of elegance and a pathway to favorable marriages. Outsiders found this practice bewildering and even horrifying, struggling to grasp the cultural ideals that made such pain desirable. The tradition, deeply rooted in social and aesthetic values, persisted for generations before finally being banned.',filetype:'image'},
{url:'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/720/Big_Buck_Bunny_720_10s_1MB.mp4',title:'Hikikomori',country:'Japan',desc:'The term Hikikomori describes a growing phenomenon in Japan where people, often young men, withdraw entirely from society—sometimes for years. Many outsiders find it difficult to understand how someone could choose such extreme isolation. But in Japan, intense social pressures, expectations of success, and close-knit family structures all contribute to this behavior. The complexity of Hikikomori challenges stereotypes about Japanese society and highlights the need for empathy and deeper understanding.',filetype:'video'},
{url:'https://cdn.historycollection.com/wp-content/uploads/2025/06/article_image_685f4a478b02a1751075399.jpg',title:'Lip Plates of the Mursi Tribe',country:'Ethiopia',desc:'Among the Mursi women of Ethiopia, wearing large clay lip plates is a time-honored tradition. The size of the plate often reflects social status and is considered a mark of beauty and maturity. For many outsiders, the sight of these dramatic adornments can be startling or even uncomfortable, as the practice defies Western ideas of aesthetics. However, for the Mursi, the lip plate is a powerful symbol of cultural identity and pride.',filetype:'image'},
{url:'https://cdn.historycollection.com/wp-content/uploads/2025/06/pexels-photo-13047140.jpg',title:'Walking Backwards for Respect',country:'China',desc:'In certain Chinese religious and traditional ceremonies, individuals demonstrate respect by walking backwards when leaving elders, temples, or sacred spaces. This symbolic gesture signifies humility and prevents turning one’s back on revered figures or holy places. To outsiders, this practice can appear unusual or even unsafe, as it defies conventional etiquette. Yet within its cultural context, walking backwards is a meaningful act of deference and reverence. ',filetype:'image'},
{url:'https://videos.pexels.com/video-files/7989672/7989672-hd_1920_1080_25fps.mp4',title:'Endlessly Coding',country:'Global',desc:'Modern endless coding has turned developers into caffeine-powered cryptids who only emerge to say, “It worked yesterday.” Their days are spent breaking things they swear they didn’t touch, Googling the same solution for the seventh time, and pasting code so cursed it should come with a warning label. Managers chant “quick fix” like it’s a spell, while the codebase grows into a wobbly tower of duct-taped functions no one fully understands. At this point the only thing truly scalable is the developer’s despair.',filetype:'video'},
{url:'https://cdn.historycollection.com/wp-content/uploads/2025/06/pexels-photo-2306282.jpg',title:'Throwing Broken Dishes at Weddings',country:'Germany',desc:'At German weddings, the Polterabend tradition calls for guests to smash porcelain dishes before the celebration. This noisy ritual is meant to sweep away bad luck and wish the couple happiness. For many outsiders, especially those from cultures where breaking dishes symbolizes misfortune, the event can seem chaotic or even alarming. However, in Germany, it’s a joyful, communal act believed to strengthen the marriage by starting fresh—together. ',filetype:'image'},
{url:'https://cdn.historycollection.com/wp-content/uploads/2025/06/article_image_685f4a934454c1751075475.jpg',title:'Yanomami Endocannibalism',country:'Country: its complicated',desc:'Among the Yanomami people of the Amazon, a profound ritual involves consuming the ashes of deceased loved ones. This practice, known as endocannibalism, is a sacred act of remembrance and a way to keep the spirit of the departed close. Outsiders often react with shock or discomfort, focusing on the act itself instead of its spiritual significance. For the Yanomami, this tradition honors family bonds and the cycle of life and death.',filetype:'image'},
{url:'https://cdn.historycollection.com/wp-content/uploads/2025/06/article_image_685f4ac1d88071751075521.jpg',title:'Famadihana: Turning of the Bones in Madagascar',country:'Madagascar',desc:'In Madagascar, the Famadihana or “Turning of the Bones” is a vibrant ceremony where families exhume ancestors’ remains, lovingly rewrap them, and celebrate with music and dance. This joyful event is meant to honor the dead, keeping their memory alive within the community. To those unaccustomed to ancestor worship, the idea of handling remains may seem unsettling or even macabre. Yet for the Malagasy, Famadihana is a powerful expression of love and familial connection.',filetype:'image'},
{url:'https://www.discovergermany.com/wp-content/uploads/2025/06/steven-weeks-p5eTjkqVcBg-unsplash.jpg',title:'Traditional Bread Making in Germany',country:'Germany',desc:'German bread is renowned for its diversity, with over 3,200 officially recognised types. From the dense and hearty rye breads of the north to the lighter wheat breads of the south, each region boasts its own specialties. This variety is also reflected in the texture, flavour, and even the shape of the loaves. The artistry of German bread lies in the meticulous techniques passed down through generations. Traditional methods are still prevalent, with bakers often starting their day in the early hours of the morning to ensure the freshest loaves. Fermentation plays a critical role. Sourdough, or Sauerteig, is a cornerstone of many German breads. The natural fermentation process not only enhances the flavour but also improves the bread’s digestibility. A good sourdough needs time to develop, and most bakers would let it ferment for up to 24 hours.',filetype:'image'},
{url:'https://i0.wp.com/thegoodlifefrance.com/wp-content/uploads/2020/10/the-good-life-france-newsletter-bread-shop.jpg?w=800&ssl=1',title:'The Art of French Bread',country:'France',desc:'There is something about French bread that we all seem to love. Bread is such a symbol of France, so ingrained in the country’s traditions that to visit a boulangerie and queue with the locals is truly one of the great cultural experiences of France. For many visitors to France, buying bread in a charming boulangerie is part of the whole experience of French-ness.  But what is it that makes us all fall in love with French bread? The taste for sure but it is more than that, the charming boulangeries, baguettes, baskets, packaging, they are all part of the gastronomic and social fabric of France.',filetype:'image'},
{url:'https://cdn.historycollection.com/wp-content/uploads/2025/06/article_image_685f4c29437941751075881.jpg',title:'La Tomatina Festival',country:'Spain',desc:'Every August, the streets of Buñol, Spain, erupt in a vivid frenzy during La Tomatina, where thousands gleefully pelt each other with ripe tomatoes. This exuberant food fight baffles many visitors, who often wonder about the festival’s origins and deeper purpose. Despite its playful chaos, La Tomatina has become a cherished local tradition and a magnet for global revelers. For outsiders, the meaning may remain elusive, but for locals, it’s a spirited celebration of fun and community.',filetype:'image'},
{url:'https://cdn.historycollection.com/wp-content/uploads/2025/06/article_image_685f4cc111a9d1751076033.jpg',title:'Walking on Fire',country:'Fiji',desc:'In Fiji, the dramatic firewalking ceremony sees participants stride barefoot across scorching hot stones—a test of spiritual power and ancestral connection. This ritual, rooted in the traditions of the Sawau people, is performed with deep reverence and communal pride. Outsiders often watch in amazement, unable to fathom how such a feat is possible or why it holds such importance. For Fijians, firewalking is a living link to their heritage, faith, and the strength of their ancestors.',filetype:'image'},
{url:'https://static.trip101.com/main_pics/25421/medium_webp.webp',title:'Hanging Coffins in Caves and on Cliffs',country:'Philippines',desc:'Traditions are rituals and beliefs that form a part of our culture. They are practiced to remind us of our history and are passed down from generation to generation. Some interesting traditions of different countries are widespread and adopted by one and all such as celebrating Christmas and birthdays, and then there are some that are quite strange or interesting and practiced only by a niche group of people. So, while you have booked rooms in one of the kid-friendly resorts in France for your upcoming family vacation or plan to spend a home-away-from-home holiday in one of the unique Airbnb vacation rentals in South Korea, you can find interesting traditions around the world on our list that are both informative and amusing - some even determine the travel dates of curious wanderers. Continue reading to delve more into the top interesting traditions from around the world.',filetype:'image'},
{url:'https://static.trip101.com/paragraph_media/pictures/002/947/311/large/Awards_ceremony_of_The_Wife_Carrying_World_Championships.jpg?1707902824',title:'Wife Carrying Championships',country:'Finland',desc:'Finland hosts an annual race that tests not only stamina, but also the relationship. The race allows three couples at a time to compete for the prize by overcoming wet and sandy obstacles. There are certain qualifications such as the wife to be carried should weigh at least 49 kg (108 lbs). Though Wife Carrying Championship is held in Sonkajärvi, Finland, there are other couples from other places who love to join the competition as well.',filetype:'image'},
{url:'https://static.trip101.com/paragraph_media/pictures/002/947/300/large/8377686712_96e9cf3df3_b.jpg?1707902822',title:'Boryeong Mud Festival',country:'South Korea',desc:'The Boryeong Mud Festival in South Korea is a fascinating and unique celebration that draws crowds from around the world. With roots dating back to 1998, this festival was initially conceived as a marketing strategy to promote the health benefits of the mineral-rich mud from the Boryeong region. It has since transformed into a major cultural event, attracting over a million visitors annually. Participants revel in various mud-related activities, including mud baths, mudslides, mud wrestling, and even a mud marathon. Beyond the therapeutic and beauty aspects of the mud, the festival features live music, food stalls, and vibrant street performances. It is a blend of wellness, recreation, and entertainment, all of which make it a truly interesting and immersive celebration.',filetype:'image'}
];

console.log(".js file working");
// for testing: image: https://www.wikihow.com/images/thumb/1/18/Make-a-Picture-Link-in-HTML-Step-6-Version-2.jpg/v4-460px-Make-a-Picture-Link-in-HTML-Step-6-Version-2.jpg
// vid: https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/720/Big_Buck_Bunny_720_10s_1MB.mp4



//source for posts: https://historycollection.com/15-cultural-practices-that-outsiders-couldnt-understand/
// https://thegoodlifefrance.com/bread-france-cultural-experience/
// https://www.discovergermany.com/the-secrets-of-german-bread-unveiling-the-craft-behind-germanys-beloved-loaves/
// https://trip101.com/article/10-interesting-traditions-around-the-world

